---

stages:  # Defining main steps of the continous integration
  - check
  - build
  - deploy
  
image: alpine #Default docker image loaded by jobs

pylint:
  stage: check
  image: linedwell/pylint:py2
  script:
    - ( pylint --output-format=colorized --disable C,R,import-error --reports=y ./*.py || pylint-exit $? ) | tee pylint.txt
  artifacts:
    paths:
      - ./pylint.txt
    expire_in: 5 min

pylint_badge:
  stage: build
  image: python:2-alpine
  variables:
    GIT_STRATEGY: none
  before_script:
    - pip install anybadge
    - mkdir -p badges
  script:
    - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
    - anybadge --value=$score --file=badges/pylint.svg pylint
  dependencies:
    - pylint
  artifacts:
    paths:
      - badges/pylint.svg
    expire_in: 5 min  
    
pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  dependencies:
    - pylint_badge
  artifacts:
    paths:
    - public/
    expire_in: 5 min  
  only:
    - master

linedbot:
  stage: deploy
  before_script:
    ## Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    #- mkdir -p ~/.ssh
    #- chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_TOKEN_L "cd $BOTDIR_L &&
        git checkout master &&
        git fetch &&
        git checkout $CI_COMMIT_SHA"
  when: manual
...