---

stages:  # Defining main steps of the continous integration
  - check

pylint:
  stage: check
  image: clburlison/pylint:py2-alpine
  before_script:
    - apk update && apk add --upgrade curl libcurl
    - curl -o pylint-exit https://raw.githubusercontent.com/jongracecox/pylint-exit/master/pylint_exit.py && chmod +x pylint-exit
  script:
    - pylint 
      --rcfile=.pylint-rcfile
      --output-format=colorized
      --disable import-error
      --reports=y
      ./*.py
  after_script:
    - ./pylint-exit $?
  when: manual
...