---

stages:  # Defining main steps of the continous integration
  - check

pylint:
  stage: check
  image: clburlison/pylint:py2-alpine
  before_script:
    - apk update && apk add --upgrade gcc py-pip python-dev
    - pip install pylint-exit
  script:
    - pylint
      --rcfile=.pylint-rcfile
      --output-format=colorized
      --disable C,R,import-error
      --reports=y
      ./*.py || pylint-exit $?
...