---

stages:  # Defining main steps of the continous integration
  - check
  - deploy

pylint:
  stage: check
  image: clburlison/pylint:py2-alpine
  before_script:
    - apk update && apk add --upgrade gcc py-pip python-dev build-base
    - pip install --no-cache-dir pylint-exit
  script:
    - pylint
      --output-format=colorized
      --disable C,R,import-error
      --reports=y
      ./*.py || pylint-exit $?
      
deploy_linedbot:
  stage: deploy
  script:
    - echo $SSH_KEY > ./sshkey
    - ssh -i ./sshkey $SSH_TOKEN_L "cd $BOTDIR_L &&
        git checkout master &&
        git fetch &&
        git checkout $CI_COMMIT_SHA &&"
  only:
    - master
  when: manual
...