---

stages:  # Defining main steps of the continous integration
  - check

pylint:
  stage: check
  image: clburlison/pylint:py2-alpine
  before_script:
    - apk update && apk add pip
    - pip install pylint-exit
  script:
    - pylint 
      --rcfile=.pylint-rcfile
      --output-format=colorized
      --disable import-error
      --reports=n
      ./*.py
    - pylint-exit $?
  when: manual
...