---

stages:  # Defining main steps of the continous integration
  - check
  - deploy

pylint:
  stage: check
  image: clburlison/pylint:py2-alpine
  before_script:
    - apk update && apk add --upgrade gcc py-pip python-dev build-base
    - pip install --no-cache-dir pylint-exit
  script:
    - pylint
      --output-format=colorized
      --disable C,R,import-error
      --reports=y
      ./*.py || pylint-exit $?

linedbot:
  stage: deploy
  before_script:
    ## Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    #- mkdir -p ~/.ssh
    #- chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_TOKEN_L "cd $BOTDIR_L &&
        git checkout master &&
        git fetch &&
        git checkout $CI_COMMIT_SHA"
  when: manual
...